import type { PublicEvent } from "./types";

export const MOCK_EVENTS: PublicEvent[] = [
  {
    id: "evt-labor-wage",
    title: "임금체불 해결 촉구 집회",
    description:
      "공식 공지에서 확인된 집회입니다. 체불임금 해결과 안전한 일터 보장을 요구하는 현장 집회로 안내되어 있습니다.",
    venue: "상암문화광장 앞",
    address: "서울 마포구 상암동",
    region: "서울",
    sourceAccountName: "민주노총",
    sourcePostUrl: "https://twitter.com/",
    issueTags: ["labor", "housing"],
    primaryIssue: "labor",
    status: "published",
    lastCheckedAt: "2026-06-05T08:12:00+09:00",
    posterImageUrl: "/posters/labor.svg",
    dates: [{ date: "2026-06-08", startTime: "14:00" }],
  },
  {
    id: "evt-climate-march",
    title: "기후위기 대응 행동의 날",
    description:
      "공식 계정의 이미지 공지와 본문을 기준으로 확인한 집회입니다. 기후위기 대응과 공공성 강화를 주요 의제로 다룹니다.",
    venue: "광화문광장 북측",
    address: "서울 종로구 세종대로",
    region: "서울",
    sourceAccountName: "기후정의행동",
    sourcePostUrl: "https://twitter.com/",
    issueTags: ["environment"],
    primaryIssue: "environment",
    status: "published",
    lastCheckedAt: "2026-06-05T08:18:00+09:00",
    posterImageUrl: "/posters/environment.svg",
    dates: [{ date: "2026-06-08", startTime: "17:00" }],
  },
  {
    id: "evt-accessibility",
    title: "장애인 이동권 보장 촉구 기자회견",
    description:
      "공식 공지 원문과 포스터를 기준으로 정리한 기자회견입니다. 이동권과 접근성 보장을 중심으로 진행됩니다.",
    venue: "서울시청 동편",
    address: "서울 중구 세종대로",
    region: "서울",
    sourceAccountName: "전장연",
    sourcePostUrl: "https://twitter.com/",
    issueTags: ["disability"],
    primaryIssue: "disability",
    status: "published",
    lastCheckedAt: "2026-06-05T08:24:00+09:00",
    posterImageUrl: "/posters/disability.svg",
    dates: [{ date: "2026-06-09", startTime: null }],
  },
  {
    id: "evt-peace-daejeon",
    title: "평화와 국제연대 문화제",
    description:
      "공식 포스트와 카드뉴스에서 확인된 문화제입니다. 평화, 반전, 국제연대 의제를 함께 다룹니다.",
    venue: "둔산동 보라매공원",
    address: "대전 서구 둔산동",
    region: "대전",
    sourceAccountName: "평화와통일을여는사람들",
    sourcePostUrl: "https://twitter.com/",
    issueTags: ["peace"],
    primaryIssue: "peace",
    status: "published",
    lastCheckedAt: "2026-06-05T08:29:00+09:00",
    posterImageUrl: "/posters/peace.svg",
    dates: [{ date: "2026-06-10", startTime: "19:00" }],
  },
  {
    id: "evt-women-work",
    title: "여성노동 권리 보장 집회",
    description:
      "공식 단체 계정의 공지를 바탕으로 정리했습니다. 여성노동, 돌봄, 차별 해소 요구를 주요 내용으로 합니다.",
    venue: "을지로입구역 4번 출구",
    address: "서울 중구 을지로",
    region: "서울",
    sourceAccountName: "여성노동네트워크",
    sourcePostUrl: "https://twitter.com/",
    issueTags: ["women", "gender", "labor"],
    primaryIssue: "women",
    status: "published",
    lastCheckedAt: "2026-06-05T08:35:00+09:00",
    posterImageUrl: "/posters/women.svg",
    dates: [{ date: "2026-06-12", startTime: "12:00" }],
  },
  {
    id: "evt-party-local",
    title: "지역 정책 공개 집회",
    description:
      "정당 공식 지역 계정 공지를 기반으로 확인한 공개 집회입니다. 정당 의제 태그는 출처 성격을 기준으로 표시됩니다.",
    venue: "부전역 광장",
    address: "부산 부산진구 부전동",
    region: "부산",
    sourceAccountName: "새길정당 부산시당",
    sourcePostUrl: "https://twitter.com/",
    issueTags: ["party"],
    primaryIssue: "party",
    status: "published",
    lastCheckedAt: "2026-06-05T08:41:00+09:00",
    posterImageUrl: "/posters/party.svg",
    dates: [{ date: "2026-06-13", startTime: "18:30" }],
  },
  {
    id: "evt-housing-jeonbuk",
    title: "공공임대 확대 촉구 집회",
    description:
      "주거권 단체 공식 공지에서 확인된 집회입니다. 공공임대 확대와 주거 안정 대책을 요구하는 지역 집회입니다.",
    venue: "전주시청 앞",
    address: "전북 전주시 완산구 노송광장로",
    region: "전북",
    sourceAccountName: "주거권연대",
    sourcePostUrl: "https://twitter.com/",
    issueTags: ["housing"],
    primaryIssue: "housing",
    status: "published",
    lastCheckedAt: "2026-06-05T08:52:00+09:00",
    posterImageUrl: "/posters/housing.svg",
    dates: [{ date: "2026-06-16", startTime: "16:00" }],
  },
  {
    id: "evt-climate-daegu",
    title: "기후정의 대구 행동",
    description:
      "공식 계정의 공개 공지를 바탕으로 확인한 집회입니다. 지역 에너지 전환과 기후정의 의제를 다룹니다.",
    venue: "동성로 광장",
    address: "대구 중구 동성로",
    region: "대구",
    sourceAccountName: "기후정의행동",
    sourcePostUrl: "https://twitter.com/",
    issueTags: ["environment"],
    primaryIssue: "environment",
    status: "published",
    lastCheckedAt: "2026-06-05T08:55:00+09:00",
    posterImageUrl: "/posters/environment.svg",
    dates: [{ date: "2026-06-20", startTime: "15:00" }],
  },
  {
    id: "evt-canceled-housing",
    title: "전세사기 대책 촉구 집회",
    description:
      "공식 취소 공지가 확인되어 공개 목록에서는 숨겨진 집회입니다.",
    venue: "국회의사당 앞",
    address: "서울 영등포구 의사당대로",
    region: "서울",
    sourceAccountName: "주거권연대",
    sourcePostUrl: "https://twitter.com/",
    cancelSourceUrl: "https://twitter.com/",
    issueTags: ["housing"],
    primaryIssue: "housing",
    status: "canceled",
    lastCheckedAt: "2026-06-05T08:46:00+09:00",
    posterImageUrl: "/posters/housing.svg",
    dates: [{ date: "2026-06-14", startTime: "15:00" }],
  },
];
